[project]
name = "personal-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "developersamim@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "gradio==4.44.1",
    "fastapi==0.115.2",
    "starlette==0.38.6",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "numpy<2",
    "onnxruntime==1.19.2",
    "pypdf>=6.19.0",
    "pydantic<2.11",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=3.3,<4",
    "torch==2.2.2",
    "transformers>=4.41,<5",
]

[project.scripts]
personal-assistant = "personal_assistant:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
